### STAGE 2: Setup ###
ARG NGINX_CONF

FROM nginx:1.13.3-alpine

## Copy our default nginx config
COPY ./front/nginx/$NGINX_CONF /etc/nginx/conf.d/

## Copy build files
COPY ./front/build /root/www

RUN chmod 755 -R /root

CMD ["nginx", "-g", "daemon off;"]
